/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme.ts
 * Command: astryx theme build theme.ts
 * Generated: 2026-07-21T01:06:21.222Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const project3Theme: DefinedTheme;
